resources:
  - name: code
    type: git
    source:
      uri: https://github.com/denissezavala/TodoListCore.git
      branch: master
  - name: pws
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{username}}
      password: {{password}}
      organization: {{organization}}
      space: {{space}}
      skip_cert_check: false

jobs:
- name: build
  plan:
  - aggregate:
    - get: code
      trigger: true
  - task: compile
    privileged: true
    file: code/pipeline/compile.yml
  - put: pws
    params: 
      manifest: code/manifest.yml