resources:
  - name: code
    type: git
    source:
      uri: https://github.com/denissezavala/TodoListCore
      branch: master

jobs:
- name: build
  plan:
  - aggregate:
    - get: code
      trigger: true
  - task: compile
    privileged: true
    file: pipeline/compile.yml