resources:
  - name: code
    type: git
    source:
      uri: https://github.com/denissezavala/TodoListCore.git
      branch: master
  - name: cf-push
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: dezavala@pivotal.io
      password: {{password}}
      organization: dezavala
      space: development
      skip_cert_check: false

jobs:
- name: build
  plan:
  - aggregate:
    - get: code
      trigger: true
  - task: compile
    privileged: true
    file: code/pipeline/compile.yml
  - put: cf-push
    params: 
      manifest: code/manifest.yml
      current_app_name: TodoListCore